# Generated by Django 4.1 on 2022-08-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='librarymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('class_name', models.CharField(default=None, max_length=10, null=True)),
                ('img', models.URLField()),
                ('url', models.URLField()),
            ],
        ),
    ]
